namespace BenMAP
{
    partial class LoadPopulationDataSet
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblPopulationDataSetName = new System.Windows.Forms.Label();
            this.grpDataSetDetail = new System.Windows.Forms.GroupBox();
            this.grpPopulationWeight = new System.Windows.Forms.GroupBox();
            this.btnBrowseDB = new System.Windows.Forms.Button();
            this.btnBrowseGW = new System.Windows.Forms.Button();
            this.txtDataBase = new System.Windows.Forms.TextBox();
            this.txtGrowthWeights = new System.Windows.Forms.TextBox();
            this.lblDatabase = new System.Windows.Forms.Label();
            this.chkPopulationGrowth = new System.Windows.Forms.CheckBox();
            this.cboGridDefinition = new System.Windows.Forms.ComboBox();
            this.grpConfiguration = new System.Windows.Forms.GroupBox();
            this.chkUseWoodsPoole = new System.Windows.Forms.CheckBox();
            this.btnView = new System.Windows.Forms.Button();
            this.btnAdd = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.cboConfiguration = new System.Windows.Forms.ComboBox();
            this.lblPopulationConfig = new System.Windows.Forms.Label();
            this.txtDataSetName = new System.Windows.Forms.TextBox();
            this.lblGridDefinition = new System.Windows.Forms.Label();
            this.grpCancelOK = new System.Windows.Forms.GroupBox();
            this.lblprogbar = new System.Windows.Forms.Label();
            this.progBarLoadPop = new System.Windows.Forms.ProgressBar();
            this.btnOK = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.timer = new System.Windows.Forms.Timer(this.components);
            this.grpDataSetDetail.SuspendLayout();
            this.grpPopulationWeight.SuspendLayout();
            this.grpConfiguration.SuspendLayout();
            this.grpCancelOK.SuspendLayout();
            this.SuspendLayout();
                                                this.lblPopulationDataSetName.AutoSize = true;
            this.lblPopulationDataSetName.Location = new System.Drawing.Point(9, 20);
            this.lblPopulationDataSetName.Name = "lblPopulationDataSetName";
            this.lblPopulationDataSetName.Size = new System.Drawing.Size(150, 14);
            this.lblPopulationDataSetName.TabIndex = 0;
            this.lblPopulationDataSetName.Text = "Population DataSet Name:";
                                                this.grpDataSetDetail.Controls.Add(this.grpPopulationWeight);
            this.grpDataSetDetail.Controls.Add(this.cboGridDefinition);
            this.grpDataSetDetail.Controls.Add(this.grpConfiguration);
            this.grpDataSetDetail.Controls.Add(this.txtDataSetName);
            this.grpDataSetDetail.Controls.Add(this.lblGridDefinition);
            this.grpDataSetDetail.Controls.Add(this.lblPopulationDataSetName);
            this.grpDataSetDetail.Location = new System.Drawing.Point(3, 3);
            this.grpDataSetDetail.Name = "grpDataSetDetail";
            this.grpDataSetDetail.Size = new System.Drawing.Size(397, 310);
            this.grpDataSetDetail.TabIndex = 1;
            this.grpDataSetDetail.TabStop = false;
                                                this.grpPopulationWeight.Controls.Add(this.btnBrowseDB);
            this.grpPopulationWeight.Controls.Add(this.btnBrowseGW);
            this.grpPopulationWeight.Controls.Add(this.txtDataBase);
            this.grpPopulationWeight.Controls.Add(this.txtGrowthWeights);
            this.grpPopulationWeight.Controls.Add(this.lblDatabase);
            this.grpPopulationWeight.Controls.Add(this.chkPopulationGrowth);
            this.grpPopulationWeight.Location = new System.Drawing.Point(6, 179);
            this.grpPopulationWeight.Name = "grpPopulationWeight";
            this.grpPopulationWeight.Size = new System.Drawing.Size(382, 125);
            this.grpPopulationWeight.TabIndex = 11;
            this.grpPopulationWeight.TabStop = false;
                                                this.btnBrowseDB.Location = new System.Drawing.Point(299, 28);
            this.btnBrowseDB.Name = "btnBrowseDB";
            this.btnBrowseDB.Size = new System.Drawing.Size(75, 27);
            this.btnBrowseDB.TabIndex = 12;
            this.btnBrowseDB.Text = "Browse";
            this.btnBrowseDB.UseVisualStyleBackColor = true;
            this.btnBrowseDB.Click += new System.EventHandler(this.btnBrowseDB_Click);
                                                this.btnBrowseGW.Location = new System.Drawing.Point(301, 87);
            this.btnBrowseGW.Name = "btnBrowseGW";
            this.btnBrowseGW.Size = new System.Drawing.Size(75, 27);
            this.btnBrowseGW.TabIndex = 11;
            this.btnBrowseGW.Text = "Browse";
            this.btnBrowseGW.UseVisualStyleBackColor = true;
            this.btnBrowseGW.Click += new System.EventHandler(this.btnBrowseGW_Click);
                                                this.txtDataBase.Location = new System.Drawing.Point(9, 31);
            this.txtDataBase.Name = "txtDataBase";
            this.txtDataBase.ReadOnly = true;
            this.txtDataBase.Size = new System.Drawing.Size(282, 22);
            this.txtDataBase.TabIndex = 8;
                                                this.txtGrowthWeights.Location = new System.Drawing.Point(9, 89);
            this.txtGrowthWeights.Name = "txtGrowthWeights";
            this.txtGrowthWeights.ReadOnly = true;
            this.txtGrowthWeights.Size = new System.Drawing.Size(282, 22);
            this.txtGrowthWeights.TabIndex = 9;
                                                this.lblDatabase.AutoSize = true;
            this.lblDatabase.Location = new System.Drawing.Point(6, 14);
            this.lblDatabase.Name = "lblDatabase";
            this.lblDatabase.Size = new System.Drawing.Size(63, 14);
            this.lblDatabase.TabIndex = 3;
            this.lblDatabase.Text = "Database:";
                                                this.chkPopulationGrowth.AutoSize = true;
            this.chkPopulationGrowth.Location = new System.Drawing.Point(9, 68);
            this.chkPopulationGrowth.Name = "chkPopulationGrowth";
            this.chkPopulationGrowth.Size = new System.Drawing.Size(199, 18);
            this.chkPopulationGrowth.TabIndex = 10;
            this.chkPopulationGrowth.Text = "Use Population Growth Weights";
            this.chkPopulationGrowth.UseVisualStyleBackColor = true;
            this.chkPopulationGrowth.CheckedChanged += new System.EventHandler(this.chkPopulationGrowth_CheckedChanged);
                                                this.cboGridDefinition.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboGridDefinition.FormattingEnabled = true;
            this.cboGridDefinition.Location = new System.Drawing.Point(165, 43);
            this.cboGridDefinition.Name = "cboGridDefinition";
            this.cboGridDefinition.Size = new System.Drawing.Size(215, 22);
            this.cboGridDefinition.TabIndex = 7;
            this.cboGridDefinition.SelectedIndexChanged += new System.EventHandler(this.cboGridDefinition_SelectedIndexChanged);
                                                this.grpConfiguration.Controls.Add(this.chkUseWoodsPoole);
            this.grpConfiguration.Controls.Add(this.btnView);
            this.grpConfiguration.Controls.Add(this.btnAdd);
            this.grpConfiguration.Controls.Add(this.btnDelete);
            this.grpConfiguration.Controls.Add(this.cboConfiguration);
            this.grpConfiguration.Controls.Add(this.lblPopulationConfig);
            this.grpConfiguration.Location = new System.Drawing.Point(6, 72);
            this.grpConfiguration.Name = "grpConfiguration";
            this.grpConfiguration.Size = new System.Drawing.Size(382, 101);
            this.grpConfiguration.TabIndex = 4;
            this.grpConfiguration.TabStop = false;
                                                this.chkUseWoodsPoole.AutoSize = true;
            this.chkUseWoodsPoole.Location = new System.Drawing.Point(9, 48);
            this.chkUseWoodsPoole.Name = "chkUseWoodsPoole";
            this.chkUseWoodsPoole.Size = new System.Drawing.Size(276, 16);
            this.chkUseWoodsPoole.TabIndex = 13;
            this.chkUseWoodsPoole.Text = "Use Woods and Poole Population Projections";
            this.chkUseWoodsPoole.UseVisualStyleBackColor = true;
                                                this.btnView.Location = new System.Drawing.Point(323, 68);
            this.btnView.Name = "btnView";
            this.btnView.Size = new System.Drawing.Size(51, 27);
            this.btnView.TabIndex = 5;
            this.btnView.Text = "View";
            this.btnView.UseVisualStyleBackColor = true;
            this.btnView.Click += new System.EventHandler(this.btnView_Click);
                                                this.btnAdd.Location = new System.Drawing.Point(266, 68);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(51, 27);
            this.btnAdd.TabIndex = 4;
            this.btnAdd.Text = "Add";
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
                                                this.btnDelete.Location = new System.Drawing.Point(201, 68);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(59, 27);
            this.btnDelete.TabIndex = 3;
            this.btnDelete.Text = "Delete";
            this.btnDelete.UseVisualStyleBackColor = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
                                                this.cboConfiguration.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConfiguration.FormattingEnabled = true;
            this.cboConfiguration.Location = new System.Drawing.Point(159, 20);
            this.cboConfiguration.Name = "cboConfiguration";
            this.cboConfiguration.Size = new System.Drawing.Size(215, 22);
            this.cboConfiguration.TabIndex = 2;
            this.cboConfiguration.SelectedIndexChanged += new System.EventHandler(this.cboConfiguration_SelectedIndexChanged);
                                                this.lblPopulationConfig.AutoSize = true;
            this.lblPopulationConfig.Location = new System.Drawing.Point(6, 20);
            this.lblPopulationConfig.Name = "lblPopulationConfig";
            this.lblPopulationConfig.Size = new System.Drawing.Size(143, 14);
            this.lblPopulationConfig.TabIndex = 1;
            this.lblPopulationConfig.Text = "Population Configuration:";
                                                this.txtDataSetName.Location = new System.Drawing.Point(165, 16);
            this.txtDataSetName.Name = "txtDataSetName";
            this.txtDataSetName.Size = new System.Drawing.Size(215, 22);
            this.txtDataSetName.TabIndex = 6;
                                                this.lblGridDefinition.AutoSize = true;
            this.lblGridDefinition.Location = new System.Drawing.Point(9, 47);
            this.lblGridDefinition.Name = "lblGridDefinition";
            this.lblGridDefinition.Size = new System.Drawing.Size(89, 14);
            this.lblGridDefinition.TabIndex = 2;
            this.lblGridDefinition.Text = "Grid Definition:";
                                                this.grpCancelOK.Controls.Add(this.lblprogbar);
            this.grpCancelOK.Controls.Add(this.progBarLoadPop);
            this.grpCancelOK.Controls.Add(this.btnOK);
            this.grpCancelOK.Controls.Add(this.btnCancel);
            this.grpCancelOK.Location = new System.Drawing.Point(3, 319);
            this.grpCancelOK.Name = "grpCancelOK";
            this.grpCancelOK.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.grpCancelOK.Size = new System.Drawing.Size(397, 74);
            this.grpCancelOK.TabIndex = 2;
            this.grpCancelOK.TabStop = false;
                                                this.lblprogbar.AutoSize = true;
            this.lblprogbar.Font = new System.Drawing.Font("Calibri", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblprogbar.ForeColor = System.Drawing.Color.Black;
            this.lblprogbar.Location = new System.Drawing.Point(8, 42);
            this.lblprogbar.Name = "lblprogbar";
            this.lblprogbar.Size = new System.Drawing.Size(0, 14);
            this.lblprogbar.TabIndex = 14;
                                                this.progBarLoadPop.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.progBarLoadPop.Location = new System.Drawing.Point(6, 18);
            this.progBarLoadPop.Name = "progBarLoadPop";
            this.progBarLoadPop.Size = new System.Drawing.Size(382, 12);
            this.progBarLoadPop.Step = 1;
            this.progBarLoadPop.TabIndex = 13;
                                                this.btnOK.Location = new System.Drawing.Point(325, 36);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(63, 27);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
                                                this.btnCancel.Location = new System.Drawing.Point(256, 36);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(63, 27);
            this.btnCancel.TabIndex = 0;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(407, 405);
            this.Controls.Add(this.grpCancelOK);
            this.Controls.Add(this.grpDataSetDetail);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimumSize = new System.Drawing.Size(413, 399);
            this.Name = "LoadPopulationDataSet";
            this.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Load Population Dataset";
            this.Load += new System.EventHandler(this.LoadPopulationDataSet_Load);
            this.grpDataSetDetail.ResumeLayout(false);
            this.grpDataSetDetail.PerformLayout();
            this.grpPopulationWeight.ResumeLayout(false);
            this.grpPopulationWeight.PerformLayout();
            this.grpConfiguration.ResumeLayout(false);
            this.grpConfiguration.PerformLayout();
            this.grpCancelOK.ResumeLayout(false);
            this.grpCancelOK.PerformLayout();
            this.ResumeLayout(false);

        }

        
        private System.Windows.Forms.Label lblPopulationDataSetName;
        private System.Windows.Forms.GroupBox grpDataSetDetail;
        private System.Windows.Forms.GroupBox grpPopulationWeight;
        private System.Windows.Forms.TextBox txtGrowthWeights;
        private System.Windows.Forms.CheckBox chkPopulationGrowth;
        private System.Windows.Forms.TextBox txtDataBase;
        private System.Windows.Forms.ComboBox cboGridDefinition;
        private System.Windows.Forms.GroupBox grpConfiguration;
        private System.Windows.Forms.Button btnView;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.ComboBox cboConfiguration;
        private System.Windows.Forms.Label lblPopulationConfig;
        private System.Windows.Forms.TextBox txtDataSetName;
        private System.Windows.Forms.Label lblDatabase;
        private System.Windows.Forms.Label lblGridDefinition;
        private System.Windows.Forms.GroupBox grpCancelOK;
        private System.Windows.Forms.Button btnOK;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnBrowseDB;
        private System.Windows.Forms.Button btnBrowseGW;
        private System.Windows.Forms.Timer timer;
        private System.Windows.Forms.ProgressBar progBarLoadPop;
        private System.Windows.Forms.Label lblprogbar;
        private System.Windows.Forms.CheckBox chkUseWoodsPoole;
    }
}